import { INormals, IWeightOfVariables } from "@/types";

export const defaultVariables: IWeightOfVariables = {
  temp: "10",
  pressure: "10",
  pressureChangingIn6Hours: "10",
  wind: "10",
  pm2_5: "10",
  kp_index: "10",
  solar_activity: "10",
};

export const defaultNormals: INormals = {
  temp: {
    from: "-10",
    to: "25",
  },
  pressure: {
    from: "720",
    to: "730",
  },
  pressureChangingIn6Hours: {
    from: "-5",
    to: "5",
  },
  wind: {
    from: "0",
    to: "10",
  },
  pm2_5: {
    from: "0",
    to: "10",
  },
  kp_index: {
    from: "0",
    to: "3",
  },
  solar_activity: {
    from: "A1",
    to: "B2",
  },
};

export const solarActivityIndexies = [
  "A1",
  "A2",
  "A3",
  "A4",
  "A5",
  "A6",
  "A7",
  "A8",
  "A9",
  "B1",
  "B2",
  "B3",
  "B4",
  "B5",
  "B6",
  "B7",
  "B8",
  "B9",
  "C1",
  "C2",
  "C3",
  "C4",
  "C5",
  "C6",
  "C7",
  "C8",
  "C9",
  "M1",
  "M2",
  "M3",
  "M4",
  "M5",
  "M6",
  "M7",
  "M8",
  "M9",
  "X1",
  "X2",
  "X3",
  "X4",
  "X5",
  "X6",
  "X7",
  "X8",
  "X9",
];

export const solarActivityIndexiesArray = [
  { title: "A1", color: "green" },
  { title: "A2", color: "green" },
  { title: "A3", color: "green" },
  { title: "A4", color: "green" },
  { title: "A5", color: "green" },
  { title: "A6", color: "green" },
  { title: "A7", color: "green" },
  { title: "A8", color: "green" },
  { title: "A9", color: "green" },
  { title: "B1", color: "green" },
  { title: "B2", color: "green" },
  { title: "B3", color: "green" },
  { title: "B4", color: "green" },
  { title: "B5", color: "green" },
  { title: "B6", color: "green" },
  { title: "B7", color: "green" },
  { title: "B8", color: "green" },
  { title: "B9", color: "green" },
  { title: "C1", color: "yellow" },
  { title: "C2", color: "yellow" },
  { title: "C3", color: "yellow" },
  { title: "C4", color: "yellow" },
  { title: "C5", color: "yellow" },
  { title: "C6", color: "yellow" },
  { title: "C7", color: "yellow" },
  { title: "C8", color: "yellow" },
  { title: "C9", color: "yellow" },
  { title: "M1", color: "orange" },
  { title: "M2", color: "orange" },
  { title: "M3", color: "orange" },
  { title: "M4", color: "orange" },
  { title: "M5", color: "orange" },
  { title: "M6", color: "orange" },
  { title: "M7", color: "orange" },
  { title: "M8", color: "orange" },
  { title: "M9", color: "orange" },
  { title: "X1", color: "red" },
  { title: "X2", color: "red" },
  { title: "X3", color: "red" },
  { title: "X4", color: "red" },
  { title: "X5", color: "red" },
  { title: "X6", color: "red" },
  { title: "X7", color: "red" },
  { title: "X8", color: "red" },
  { title: "X9", color: "red" },
];
